import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { StarsBackground } from "@/components/ui/stars-background";
import { ShootingStars } from "@/components/ui/shooting-stars";
import TransitionWrapper from "@/components/TransitionWrapper";

const firaCode = Fira_Code({
    variable: "--font-fira-code",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "aryansharma2k4",
    description: "Generated by create next app",
    icons:{
        icon: "/commandLineStart.svg"
    }

};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${firaCode.variable} font-mono antialiased flex flex-col bg-black min-h-screen md:mx-[20%] sm:mx-[10%] mx-[5%]`}>


        <div className="relative z-10"><TransitionWrapper>
            <Navbar />
            <main className="flex-grow relative z-10">{children}</main>
        </TransitionWrapper></div>
        <StarsBackground className="fixed z-0" starDensity={0.0006} />

        <ShootingStars maxDelay={1000} starWidth={20} starHeight={2} minDelay={500} className="absolute z-0" />
        </body>
        </html>
    );
}
